package com.system.wash.controller;

import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import com.system.wash.entity.WashScheduleBean;
import com.system.wash.service.WashScheduleService;

@RestController
@CrossOrigin
public class WashScheduleAjaxController {

    @Autowired
    private WashScheduleService WashScheduleService;

    @PostMapping("/ajax/pages/WashSchedules/find")
    public String find(@RequestBody String body) {

        JSONObject responseJson = new JSONObject();

        long count = WashScheduleService.count(body);
        responseJson.put("count", count);

        JSONArray array = new JSONArray();

        List<WashScheduleBean> schedules = WashScheduleService.find(body);

        if (schedules != null && !schedules.isEmpty()) {

            for (WashScheduleBean schedule : schedules) {

                JSONObject item = new JSONObject()
                        .put("scheduleId", schedule.getScheduleId())
                        .put("slotTemplateId", schedule.getSlotTemplateId())
                        .put("workDate", schedule.getWorkDate())
                        .put("slotIndex", schedule.getSlotIndex())
                        .put("periodOfDayId", schedule.getPeriodOfDayId())
                        .put("isAvailable", schedule.getIsAvailable())
                        .put("apptOrderId", schedule.getApptOrderId())
                        .put("note", schedule.getNote())
                        .put("createdAt", schedule.getCreatedAt())
                        .put("updatedAt", schedule.getUpdatedAt())
                        .put("isAutoGenerated", schedule.getIsAutoGenerated());

                array.put(item);
            }
        }

        responseJson.put("list", array);

        return responseJson.toString();
    }

    @GetMapping("/ajax/pages/WashSchedules/{id}")
    public String findById(@PathVariable Integer id) {

        JSONObject responseJson = new JSONObject();

        JSONArray array = new JSONArray();

        WashScheduleBean schedule = WashScheduleService.findById(id);

        if (schedule != null) {

            JSONObject item = new JSONObject()
                    .put("scheduleId", schedule.getScheduleId())
                    .put("slotTemplateId", schedule.getSlotTemplateId())
                    .put("workDate", schedule.getWorkDate())
                    .put("slotIndex", schedule.getSlotIndex())
                    .put("periodOfDayId", schedule.getPeriodOfDayId())
                    .put("isAvailable", schedule.getIsAvailable())
                    .put("apptOrderId", schedule.getApptOrderId())
                    .put("note", schedule.getNote())
                    .put("createdAt", schedule.getCreatedAt())
                    .put("updatedAt", schedule.getUpdatedAt())
                    .put("isAutoGenerated", schedule.getIsAutoGenerated());

            array.put(item);
        }

        responseJson.put("list", array);

        return responseJson.toString();
    }

    @PostMapping("/ajax/pages/WashSchedules")
    public String create(@RequestBody String body) {

        JSONObject responseJson = new JSONObject();

        WashScheduleBean insert = WashScheduleService.create(body);

        if (insert == null) {
            responseJson.put("success", false);
            responseJson.put("message", "OK");
        } else {
            responseJson.put("success", true);
            responseJson.put("message", "OK");

            // ???澈?芸?????ID ?蝯血?蝡荔??嫣噶?垢敺?啗??? ID
            responseJson.put("scheduleId", insert.getScheduleId());
        }

        return responseJson.toString();
    }

    @PutMapping("/ajax/pages/WashSchedules/{id}")
    public String modify(
            @PathVariable Integer id,
            @RequestBody String body) {

        JSONObject responseJson = new JSONObject();

        if (id == null) {

            responseJson.put("success", false);
            responseJson.put("message", "ScheduleId是必要欄位");

        } else if (!WashScheduleService.exists(id)) {

            responseJson.put("success", false);
            responseJson.put("message", "ScheduleId不存在");

        } else {

            WashScheduleBean update = WashScheduleService.modify(body);

            if (update == null) {

                responseJson.put("success", false);
                responseJson.put("message", "修改失敗");

            } else {

                responseJson.put("success", true);
                responseJson.put("message", "修改成功");
            }
        }

        return responseJson.toString();
    }

    @DeleteMapping("/ajax/pages/WashSchedules/{id}")
    public String remove(@PathVariable Integer id) {

        JSONObject responseJson = new JSONObject();

        if (id == null) {

            responseJson.put("success", false);
            responseJson.put("message", "ScheduleId是必要欄位");

        } else if (!WashScheduleService.exists(id)) {

            responseJson.put("success", false);
            responseJson.put("message", "ScheduleId不存在");

        } else {

            boolean result = WashScheduleService.remove(id);

            if (!result) {

                responseJson.put("success", false);
                responseJson.put("message", "刪除失敗");

            } else {

                responseJson.put("success", true);
                responseJson.put("message", "刪除成功");
            }
        }

        return responseJson.toString();
    }

    // 1. GET /api/schedules - 取得全部班表
    @GetMapping("/api/schedules")
    public String getAllSchedules() {
        List<WashScheduleBean> schedules = WashScheduleService.findAllSchedules();
        return convertScheduleListToJson(schedules);
    }

    @GetMapping("/ajax/pages/WashSchedules/all")
    public String findAllSchedulesAjax() {
        List<WashScheduleBean> schedules = WashScheduleService.findAllSchedules();
        return convertScheduleListToJson(schedules);
    }

    // 2. GET /api/schedules/{date} - 取得某天班表 (例如: /api/schedules/2026-06-09)
    @GetMapping("/api/schedules/{date}")
    public String getSchedulesByDate(@PathVariable String date) {
        List<WashScheduleBean> schedules = WashScheduleService.findSchedulesByDate(date);
        return convertScheduleListToJson(schedules);
    }

    // 3. GET /ajax/pages/WashSchedules/workDate/{workDate} - 根據 workDate 查詢該日所有預約時段
    @GetMapping("/ajax/pages/WashSchedules/workDate/{workDate}")
    public String findByWorkDate(@PathVariable String workDate) {
        List<WashScheduleBean> schedules = WashScheduleService.findSchedulesByDate(workDate);
        return convertScheduleListToJson(schedules);
    }

    // 4. GET /ajax/pages/WashSchedules/available/{workDate} - 根據 workDate 查詢該日「可預約」的時段
    @GetMapping("/ajax/pages/WashSchedules/available/{workDate}")
    public String findAvailableByWorkDate(@PathVariable String workDate) {
        List<WashScheduleBean> schedules = WashScheduleService.findSchedulesByDate(workDate);
        JSONObject responseJson = new JSONObject();
        JSONArray array = new JSONArray();

        if (schedules != null && !schedules.isEmpty()) {
            for (WashScheduleBean schedule : schedules) {
                // 篩選出 isAvailable 為 true 的可預約時段
                if (Boolean.TRUE.equals(schedule.getIsAvailable())) {
                    JSONObject item = new JSONObject()
                            .put("scheduleId", schedule.getScheduleId())
                            .put("slotTemplateId", schedule.getSlotTemplateId())
                            .put("workDate", schedule.getWorkDate())
                            .put("slotIndex", schedule.getSlotIndex())
                            .put("periodOfDayId", schedule.getPeriodOfDayId())
                            .put("isAvailable", schedule.getIsAvailable())
                            .put("apptOrderId", schedule.getApptOrderId())
                            .put("note", schedule.getNote())
                            .put("createdAt", schedule.getCreatedAt())
                            .put("updatedAt", schedule.getUpdatedAt())
                            .put("isAutoGenerated", schedule.getIsAutoGenerated());
                    array.put(item);
                }
            }
        }
        responseJson.put("list", array);
        return responseJson.toString();
    }

    // 5. GET /ajax/pages/WashSchedules/slotIndex/{slotIndex} - 根據 slotIndex 查詢所有預約時段
    @GetMapping("/ajax/pages/WashSchedules/slotIndex/{slotIndex}")
    public String findBySlotIndex(@PathVariable Integer slotIndex) {
        List<WashScheduleBean> schedules = WashScheduleService.findSchedulesBySlotIndex(slotIndex);
        return convertScheduleListToJson(schedules);
    }

    //將 List 轉成JSONObject 字串
    private String convertScheduleListToJson(List<WashScheduleBean> schedules) {
        JSONObject responseJson = new JSONObject();
        JSONArray array = new JSONArray();

        if (schedules != null && !schedules.isEmpty()) {
            for (WashScheduleBean schedule : schedules) {
                JSONObject item = new JSONObject()
                        .put("scheduleId", schedule.getScheduleId())
                        .put("slotTemplateId", schedule.getSlotTemplateId())
                        .put("workDate", schedule.getWorkDate())
                        .put("slotIndex", schedule.getSlotIndex())
                        .put("periodOfDayId", schedule.getPeriodOfDayId())
                        .put("isAvailable", schedule.getIsAvailable())
                        .put("apptOrderId", schedule.getApptOrderId())
                        .put("note", schedule.getNote())
                        .put("createdAt", schedule.getCreatedAt())
                        .put("updatedAt", schedule.getUpdatedAt())
                        .put("isAutoGenerated", schedule.getIsAutoGenerated());



                array.put(item);
            }
        }
        responseJson.put("list", array);
        return responseJson.toString();
    }
}
