package com.system.wash.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "WashSchedule")
public class WashScheduleBean {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "schedule_id")
    private Integer scheduleId;

    @Column(name = "slot_template_id")
    private Integer slotTemplateId;

    @Column(name = "work_date", nullable = false)
    private LocalDate workDate;

    @Column(name = "slot_index")
    private Byte slotIndex;

    @Column(name = "period_of_day_id")
    private Integer periodOfDayId;

    @Column(name = "is_available", nullable = false)
    private Boolean isAvailable = true;

    @Column(name = "appt_order_id")
    private Integer apptOrderId;

    @Column(name = "note", length = 500)
    private String note;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated;

    @Override
    public String toString() {
        return "WashScheduleBean [scheduleId=" + scheduleId
                + ", slotTemplateId=" + slotTemplateId
                + ", workDate=" + workDate
                + ", slotIndex=" + slotIndex
                + ", periodOfDayId=" + periodOfDayId
                + ", isAvailable=" + isAvailable
                + ", apptOrderId=" + apptOrderId
                + ", note=" + note
                + ", createdAt=" + createdAt
                + ", updatedAt=" + updatedAt
                + ", isAutoGenerated=" + isAutoGenerated
                + "]";
    }

    public Integer getScheduleId() {
        return scheduleId;
    }

    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    public Integer getSlotTemplateId() {
        return slotTemplateId;
    }

    public void setSlotTemplateId(Integer slotTemplateId) {
        this.slotTemplateId = slotTemplateId;
    }

    public LocalDate getWorkDate() {
        return workDate;
    }

    public void setWorkDate(LocalDate workDate) {
        this.workDate = workDate;
    }

    public Byte getSlotIndex() {
        return slotIndex;
    }

    public void setSlotIndex(Byte slotIndex) {
        this.slotIndex = slotIndex;
    }

    public Integer getPeriodOfDayId() {
        return periodOfDayId;
    }

    public void setPeriodOfDayId(Integer periodOfDayId) {
        this.periodOfDayId = periodOfDayId;
    }

    public Boolean getIsAvailable() {
        return isAvailable;
    }

    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    public Integer getApptOrderId() {
        return apptOrderId;
    }

    public void setApptOrderId(Integer apptOrderId) {
        this.apptOrderId = apptOrderId;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }
}
