package com.system.wash.service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.system.wash.repository.WashScheduleDAO;
import com.system.wash.entity.WashScheduleBean;
import com.system.wash.repository.WashScheduleRepository;
import com.system.wash.entity.WashWorkCalendarBean;
import com.system.wash.entity.WashCalendarPeriodBean;
import com.system.wash.repository.WashWorkCalendarRepository;
import com.system.wash.repository.WashCalendarPeriodRepository;
import org.springframework.transaction.annotation.Transactional;

import java.util.Collections;


@Service
public class WashScheduleService {

    @Autowired
    private WashScheduleRepository WashScheduleRepository;

    @Autowired
    private WashScheduleDAO washScheduleDAO;

    @Autowired
    private WashWorkCalendarRepository washWorkCalendarRepository;

    @Autowired
    private WashCalendarPeriodRepository washCalendarPeriodRepository;

    public List<WashScheduleBean> findAll() {
        return WashScheduleRepository.findAll();
    }

    public List<WashScheduleBean> find(String json) {
        try {
            JSONObject obj = new JSONObject(json);
            return washScheduleDAO.find(obj);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return null;
    }

    public long count(String json) {
        try {
            JSONObject obj = new JSONObject(json);
            return washScheduleDAO.count(obj);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return 0;
    }

    public WashScheduleBean findById(Integer scheduleId) {
        if (scheduleId != null) {
            return WashScheduleRepository.findById(scheduleId).orElse(null);
        }
        return null;
    }

    public boolean exists(Integer scheduleId) {
        return WashScheduleRepository.existsById(scheduleId);
    }

    public List<WashScheduleBean> select(WashScheduleBean bean) {
        List<WashScheduleBean> result = null;

        if (bean != null
                && bean.getScheduleId() != null
                && !bean.getScheduleId().equals(0)) {

            WashScheduleBean temp = WashScheduleRepository.findById(bean.getScheduleId())
                    .orElse(null);

            if (temp != null) {
                result = new ArrayList<>();
                result.add(temp);
            }

        } else {
            result = WashScheduleRepository.findAll();
        }

        return result;
    }

    @Transactional
    public WashScheduleBean create(String json) {
        try {
            JSONObject obj = new JSONObject(json);

            Integer scheduleId = obj.isNull("scheduleId") ? null : obj.getInt("scheduleId");

            Integer slotTemplateId = obj.isNull("slotTemplateId") ? null : obj.getInt("slotTemplateId");

            String workDate = obj.isNull("workDate") ? null : obj.getString("workDate");

            Byte slotIndex = obj.isNull("slotIndex") ? null : (byte) obj.getInt("slotIndex");

            Boolean isAvailable = obj.isNull("isAvailable") ? null : obj.getBoolean("isAvailable");

            Integer apptOrderId = readNullableInteger(obj, "apptOrderId");

            String note = obj.isNull("note") ? null : obj.getString("note");

            Boolean isAutoGenerated = obj.isNull("isAutoGenerated") ? null : obj.getBoolean("isAutoGenerated");

            // 如果是自動遞增，scheduleId 為 null 是正確的，不應該去查 existsById
            if (scheduleId == null || !WashScheduleRepository.existsById(scheduleId)) {

                WashScheduleBean insert = new WashScheduleBean();

                insert.setScheduleId(scheduleId); // 此處傳入 null，Hibernate 會觸發資料庫自動遞增
                insert.setSlotTemplateId(slotTemplateId);

                // 將前端傳入的字串 workDate 轉為 Date 物件（避免原本寫 null 導致資料庫漏欄位）
                if (workDate != null) {
                    insert.setWorkDate(LocalDate.parse(workDate));
                } else {
                    insert.setWorkDate(null);
                }

                insert.setSlotIndex(slotIndex);
                if (apptOrderId != null) {
                    insert.setIsAvailable(false);
                } else {
                    insert.setIsAvailable(isAvailable != null ? isAvailable : true);
                }
                insert.setApptOrderId(apptOrderId);
                insert.setNote(note);

                insert.setCreatedAt(LocalDateTime.now());
                insert.setUpdatedAt(LocalDateTime.now());

                insert.setIsAutoGenerated(isAutoGenerated);

                WashScheduleBean saved = WashScheduleRepository.save(insert);
                syncCalendarPeriod(saved);
                return saved;
            } else {
                System.out.println("Create schedule skipped: scheduleId already exists: " + scheduleId);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return null;
    }

    @Transactional
    public WashScheduleBean insert(WashScheduleBean bean) {

        if (bean != null && bean.getScheduleId() != null) {

            WashScheduleBean temp = WashScheduleRepository.findById(bean.getScheduleId())
                    .orElse(null);

            if (temp == null) {
                bean.setCreatedAt(LocalDateTime.now());
                bean.setUpdatedAt(LocalDateTime.now());

                WashScheduleBean saved = WashScheduleRepository.save(bean);
                syncCalendarPeriod(saved);
                return saved;
            }
        }

        return null;
    }

    @Transactional
    public WashScheduleBean modify(String json) {

        try {

            JSONObject obj = new JSONObject(json);

            Integer scheduleId = obj.isNull("scheduleId") ? null : obj.getInt("scheduleId");

            WashScheduleBean update = WashScheduleRepository.findById(scheduleId)
                    .orElse(null);

            if (update != null) {

                if (!obj.isNull("slotTemplateId")) {
                    update.setSlotTemplateId(obj.getInt("slotTemplateId"));
                }

                if (!obj.isNull("slotIndex")) {
                    update.setSlotIndex((byte) obj.getInt("slotIndex"));
                }

                if (!obj.isNull("isAvailable")) {
                    update.setIsAvailable(obj.getBoolean("isAvailable"));
                }

                if (!obj.isNull("apptOrderId")) {
                    Integer newApptOrderId = readNullableInteger(obj, "apptOrderId");
                    if (newApptOrderId != null) {
                        // Double booking check
                        if (update.getApptOrderId() != null) {
                            if (!update.getApptOrderId().equals(newApptOrderId)) {
                                System.out.println("Modify schedule skipped: slot is already booked by appointment: " + update.getApptOrderId());
                                return null;
                            }
                        }
                        update.setApptOrderId(newApptOrderId);
                        update.setIsAvailable(false);
                    } else {
                        update.setApptOrderId(null);
                        update.setIsAvailable(true);
                    }
                }

                if (!obj.isNull("note")) {
                    update.setNote(obj.getString("note"));
                }

                if (!obj.isNull("isAutoGenerated")) {
                    update.setIsAutoGenerated(obj.getBoolean("isAutoGenerated"));
                }

                update.setUpdatedAt(LocalDateTime.now());

                WashScheduleBean saved = WashScheduleRepository.save(update);
                syncCalendarPeriod(saved);
                return saved;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return null;
    }

    @Transactional
    public WashScheduleBean update(WashScheduleBean bean) {

        if (bean != null && bean.getScheduleId() != null) {

            WashScheduleBean update = WashScheduleRepository.findById(bean.getScheduleId())
                    .orElse(null);

            if (update != null) {

                bean.setCreatedAt(update.getCreatedAt());
                bean.setUpdatedAt(LocalDateTime.now());

                WashScheduleBean saved = WashScheduleRepository.save(bean);
                syncCalendarPeriod(saved);
                return saved;
            }
        }

        return null;
    }

    @Transactional
    public boolean remove(Integer scheduleId) {

        try {

            WashScheduleBean schedule = WashScheduleRepository.findById(scheduleId).orElse(null);
            if (schedule != null) {
                
                WashScheduleRepository.deleteById(scheduleId);

                // 刪除等同於關閉該時段，連動行事曆設定
                schedule.setIsAvailable(false);
                syncCalendarPeriod(schedule);
                
                return true;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return false;
    }

    @Transactional
    public boolean delete(WashScheduleBean bean) {

        if (bean != null && bean.getScheduleId() != null) {

            WashScheduleBean result = WashScheduleRepository.findById(bean.getScheduleId())
                    .orElse(null);

            if (result != null) {

                WashScheduleRepository.delete(result);

                // 刪除等同於關閉該時段，連動行事曆設定
                result.setIsAvailable(false);
                syncCalendarPeriod(result);
                
                return true;
            }
        }

        return false;
    }

    /**
     * 反向連動：當 WashSchedule (預約時段) 被修改/刪除時，同步更新 WashWorkCalendar (行事曆設定)
     */
    private void syncCalendarPeriod(WashScheduleBean schedule) {
        if (schedule == null || schedule.getWorkDate() == null || schedule.getPeriodOfDayId() == null) {
            return;
        }
        WashWorkCalendarBean calendar = washWorkCalendarRepository.findByWorkDate(schedule.getWorkDate());
        if (calendar != null) {
            List<WashCalendarPeriodBean> periods = washCalendarPeriodRepository.findByCalendarId(calendar.getCalendarId());
            boolean periodFound = false;
            
            // 檢查該日期該時段下，是否有任何時段是開放的 (isAvailable == true) 或已被預約 (apptOrderId != null)
            List<WashScheduleBean> allSchedules = WashScheduleRepository.findByWorkDate(schedule.getWorkDate());
            boolean isActivePeriod = false;
            if (allSchedules != null) {
                for (WashScheduleBean s : allSchedules) {
                    if (s.getPeriodOfDayId() != null && s.getPeriodOfDayId().equals(schedule.getPeriodOfDayId())) {
                        boolean isBooked = s.getApptOrderId() != null;
                        if (Boolean.TRUE.equals(s.getIsAvailable()) || isBooked) {
                            isActivePeriod = true;
                            break;
                        }
                    }
                }
            }

            for (WashCalendarPeriodBean period : periods) {
                if (period.getPeriodOfDayId().equals(schedule.getPeriodOfDayId())) {
                    period.setIsActive(isActivePeriod);
                    washCalendarPeriodRepository.save(period);
                    periodFound = true;
                    break;
                }
            }
            // 若排班表新增了一個原本沒開的時段，則連動加回 CalendarPeriod 中
            if (!periodFound && isActivePeriod) {
                WashCalendarPeriodBean newPeriod = new WashCalendarPeriodBean();
                newPeriod.setCalendarId(calendar.getCalendarId());
                newPeriod.setPeriodOfDayId(schedule.getPeriodOfDayId());
                newPeriod.setIsActive(true);
                washCalendarPeriodRepository.save(newPeriod);
            }
        }
    }

    // 取得全部班表
    public List<WashScheduleBean> findAllSchedules() {
        return WashScheduleRepository.findAll();
    }

    // 取得某天班表
    public List<WashScheduleBean> findSchedulesByDate(String dateStr) {
        if (dateStr != null) {
            try {
                LocalDate workDate = LocalDate.parse(dateStr);
                return WashScheduleRepository.findByWorkDate(workDate);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return new ArrayList<>();
    }

    public List<WashScheduleBean> findSchedulesBySlotIndex(Integer slotIndex) {
        // 基本防呆檢查，如果傳入的 slotIndex 為空，則回傳空列表
        if (slotIndex == null) {
            return Collections.emptyList();
        }
        
        // 呼叫 Repository 的方法來取得資料
        return WashScheduleRepository.findBySlotIndex(slotIndex.byteValue());
    }

    private Integer readNullableInteger(JSONObject obj, String key) {
        if (obj.isNull(key)) {
            return null;
        }

        String value = obj.optString(key, null);
        if (value == null || value.trim().isEmpty() || value.equalsIgnoreCase("null")) {
            return null;
        }

        return Integer.valueOf(value);
    }
}
